on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'psalm.xml'

  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'psalm.xml'

name: Mutation test

jobs:
  mutation:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - '8.0'
          - '8.1'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run infection
        run: |
          docker-compose -f tests/docker/docker-compose.yml build --pull php${{ matrix.php }}
          docker-compose -f tests/docker/docker-compose.yml run php${{ matrix.php }} php -dpcov.enabled=1 -dpcov.directory=. vendor/bin/roave-infection-static-analysis-plugin -j2 --ignore-msi-with-no-mutations --only-covered
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}