on:
  pull_request:
    branches: [ "main" ]

name: Static analysis

jobs:
  psalm:
    name: PHP ${{ matrix.php }}
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          php: [ 80, 81 ]
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Build
          run: make build