name: Run tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  psalm:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0', '8.1' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run PHPUnit
        run: make test v=${{ matrix.php }}